{
  "openapi": "3.0.3",
  "info": {
    "title": "Ticket System",
    "version": "0.0.1"
  },
  "paths": {
    "/tickets/createdBy/users/{userId}": {
      "get": {
        "description": "Get all tickets created by a user id.",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ticketModelList": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Ticket"
                      }
                    }
                  },
                  "example": {
                    "ticketModelList": [
                      {
                        "ticketId": "fLgkT",
                        "shortDescription": "Issue1",
                        "longDescription": "Job1 abended.",
                        "assignedToUserId": "1",
                        "createdByUserId": "2",
                        "state": "OPEN",
                        "resolutionText": "N/A",
                        "creationDate": "2024-01-26"
                      },
                      {
                        "ticketId": "EEcYX",
                        "shortDescription": "Issue2",
                        "longDescription": "Job2 abended.",
                        "assignedToUserId": "2",
                        "createdByUserId": "2",
                        "state": "CLOSED",
                        "resolutionText": "Reran job.",
                        "creationDate": "2024-01-26"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tickets/assignedTo/users/{userId}": {
      "get": {
        "description": "Get all tickets assigned to a user id.",
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ticketModelList": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Ticket"
                      }
                    }
                  },
                  "example": {
                    "ticketModelList": [
                      {
                        "ticketId": "fLgkT",
                        "shortDescription": "Issue1",
                        "longDescription": "Job1 abended.",
                        "assignedToUserId": "2",
                        "createdByUserId": "1",
                        "state": "OPEN",
                        "resolutionText": "N/A",
                        "creationDate": "2024-01-26"
                      },
                      {
                        "ticketId": "EEcYX",
                        "shortDescription": "Issue2",
                        "longDescription": "Job2 abended.",
                        "assignedToUserId": "2",
                        "createdByUserId": "2",
                        "state": "CLOSED",
                        "resolutionText": "Reran job.",
                        "creationDate": "2024-01-26"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tickets/users/{createdByUserId}": {
      "post": {
        "description": "Used to create a new ticket.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "shortDescription": {
                    "type": "string"
                  },
                  "longDescription": {
                    "type": "string"
                  },
                  "assignedToUserId": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "shortDescription": "Issue",
                "longDescription": "Production job abended.",
                "assignedToUserId": "1"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "createdByUserId",
            "in": "path",
            "description": "Id of user creating ticket.",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "2"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ticket": {
                      "$ref": "#/components/schemas/Ticket"
                    }
                  },
                  "example": {
                    "ticket": {
                      "ticketId": "fLgkT",
                      "shortDescription": "Issue",
                      "longDescription": "Production job abended.",
                      "assignedToUserId": "1",
                      "createdByUserId": "2",
                      "state": "OPEN",
                      "resolutionText": "N/A",
                      "creationDate": "2024-01-26"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tickets/{ticketId}": {
      "put": {
        "description": "Used to resolve a ticket.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "resolutionText": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  },
                  "userId": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "resolutionText": "Reran job.",
                "state": "CLOSED",
                "userId": "2"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "ticketId",
            "in": "path",
            "description": "Id of the ticket to resolve.",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "fLgkT"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ticket": {
                      "$ref": "#/components/schemas/Ticket"
                    }
                  },
                  "example": {
                    "ticket": {
                      "ticketId": "fLgkT",
                      "shortDescription": "Issue",
                      "longDescription": "Description",
                      "assignedToUserId": "2",
                      "createdByUserId": "1",
                      "state": "CLOSED",
                      "resolutionText": "Reran job.",
                      "creationDate": "2024-01-26"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "Used to get a ticket.",
        "parameters": [
          {
            "name": "ticketId",
            "in": "path",
            "description": "Id of the ticket to retrieve.",
            "required": true,
            "schema": {
              "type": "string"
            },
            "example": "fLgkT"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "ticket": {
                      "$ref": "#/components/schemas/Ticket"
                    }
                  },
                  "example": {
                    "ticket": {
                      "ticketId": "fLgkT",
                      "shortDescription": "Issue",
                      "longDescription": "Description",
                      "assignedToUserId": "1",
                      "createdByUserId": "1",
                      "state": "OPEN",
                      "resolutionText": "N/A",
                      "creationDate": "2024-01-26"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "Used to get all users.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Users"
                  },
                  "example": {
                    "userList": [
                      {
                        "id": "1",
                        "name": "Swastik"
                      },
                      {
                        "id": "2",
                        "name": "Steve"
                      },
                      {
                        "id": "3",
                        "name": "Tom"
                      }
                    ]
                  }
                }
              }
            }
          },
          "400": {
            "description": "Client Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 400,
                    "message": "Client error"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Error"
                  },
                  "example": {
                    "code": 500,
                    "message": "Server error"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Users": {
        "type": "object",
        "properties": {
          "userList": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Ticket": {
        "type": "object",
        "properties": {
          "ticketId": {
            "type": "string"
          },
          "longDescription": {
            "type": "string"
          },
          "shortDescription": {
            "type": "string"
          },
          "assignedToUserId": {
            "type": "string"
          },
          "createdByUserId": {
            "type": "string"
          },
          "creationDate": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "resolutionText": {
            "type": "string"
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}